### ISSUE TITLE
what's the idea behind APP_NAME environment variable?

### ISSUE THREAD

**Issue by AleXoundOS** [lucasew/nixcfg#6]
https://github.com/lucasew/nixcfg/blob/ba7cf66c70ec07a81188bc58f33863caac253456/pkgs/wrapWine.nix#L53

It is not used anywhere in the script. At least directly.

**Comment by lucasew** [comment]
The idea is to use it in the installer script

BTW these scripts are deprecated, I was doing a more final solution on nixpkgs-brasil
