### ISSUE TITLE
is there any implications of reassigning the HOME environment variable?

### ISSUE THREAD

**Issue by AleXoundOS** [lucasew/nixcfg#7]
https://github.com/lucasew/nixcfg/blob/24bd0f2a3cbb8cd51e11a35ddf33019d968b104d/pkgs/wrapWine.nix#L58

**Comment by AleXoundOS** [comment]
It seems it prevents wine from running GUI applications...

**Comment by lucasew** [comment]
The idea here is to redirect some app state/settings to another folder instead of the obscure folder that is in the prefix
