### ISSUE TITLE
wrapWine application versioning & desktop entry icons

### ISSUE THREAD

**Issue by dzervas** [lucasew/nixcfg#9]
Hello!

I successfully package [EstlCAM](https://estlcam.de) using your `wrapWine` module but I have some suggestions/questions:

1. Since the script isn't version-aware it's not able to implement updates later on (e.g. by re-running the `firstrunScript` or a custom `upgradeScript`
2. How can I access an icon inside the wineprefix after the firstrunscript has ran? The idea is to create a desktop entry with the icon taken from inside the installation folder

Thank you!

**Comment by lucasew** [comment]
To get the icon you will need to run that first run part first then copy the icon to the code. I don't know any other way

BTW this is a personal repo and things may and probably will break without warning.

Today I basically only use this primitive with 7zip.

**Comment by dzervas** [comment]
No worries! More of a suggestion than a request - I use it on my personal repo too

BTW here's how I use it: https://github.com/dzervas/dotfiles/blob/main/home/wine/estlcam.nix
